### ISSUE TITLE
Output static lib file in build process.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/ax#7]
Unlike in .NET, you can't statically-link against an .exe file (AFAIK). Thus, we need to produce a proper lib file against which users can statically-link.

**Comment by nabijaczleweli** [comment]
If you're outputting 2/3 binaries using only Makefiles, it's time to consider CMake, IMO
Otherwise you end up with [this](https://github.com/nabijaczleweli/Cwepper/blob/master/Makefile) abomination.

**Comment by bryanedds** [comment]
CMake sends shivers down my spine... but point taken that a better general approach may be warranted.

**Comment by nabijaczleweli** [comment]
Lemme get this straight, CMake is not _great_ and is horrible to maintain, but it gets the job done. I don't think writing an abomination Makefile like the above is a good idea.

**Comment by bryanedds** [comment]
Done.
